--- #YAML:1.0
name: DateTime-Calendar-Mayan
version: 0.04
license: perl
distribution_type: module
requires:
  DateTime: 0.08
  Params::Validate: 0.52
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Calendar::Mayan:
    file: lib/DateTime/Calendar/Mayan.pm
    version: 0.04
generated_by: Module::Build version 0.18
