--- #YAML:1.0
name: DateTime-Calendar-Mayan
version: 0.06
license: perl
distribution_type: module
requires:
  DateTime: 0.15
  Params::Validate: 0.64
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.17
